language: elixir

matrix:
  include:
    - otp_release: 19.0
      elixir: 1.3.4
    - otp_release: 19.3
      elixir: 1.4.5
    - otp_release: 20.0
      elixir: 1.5.1

services:
  - redis-server

sudo: false # to use faster container based build environment

script:
  - MIX_ENV=test mix coveralls.travis
