language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 19.2
      elixir: 1.4.0

services:
  - redis-server

sudo: false # to use faster container based build environment

script:
  - MIX_ENV=test mix coveralls.travis
