language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.2
    - otp_release: 19.0
      elixir: 1.3.2

services:
  - redis-server
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
install:
  - mix local.hex --force
  - mix deps.get --only test
script:
  - mix test --trace
