language: elixir

elixir:
  - 1.2.6
  - 1.3.4

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 18.3
      elixir: 1.3.4
    - otp_release: 19.3
      elixir: 1.3.4

services:
  - redis-server
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
script:
  - MIX_ENV=test mix coveralls.travis
